#Total revenue?
SELECT SUM(REVENUE) FROM `INDIAN FMCG`
#Total cost?
SELECT SUM(COST) FROM `INDIAN FMCG`
#Total profit?
SELECT SUM(MARGIN) FROM `INDIAN FMCG`
#Total units sold?
SELECT SUM(UNITS) FROM `INDIAN FMCG`
#Total transactions?
SELECT COUNT(UNITS) FROM `INDIAN FMCG`
#Monthly revenue?
SELECT MONTHNAME(INVOICE_DATE) AS MONTH ,SUM(REVENUE) AS REVENUE FROM `INDIAN FMCG`
GROUP BY MONTH(INVOICE_DATE), MONTHNAME(INVOICE_DATE) ORDER BY MONTH(INVOICE_DATE) ASC;
#Monthly profit?
SELECT MONTHNAME(INVOICE_DATE) AS MONTH ,SUM(MARGIN) AS MARGIN FROM `INDIAN FMCG`
GROUP BY MONTH(INVOICE_DATE), MONTHNAME(INVOICE_DATE) ORDER BY MONTH(INVOICE_DATE) ASC;
#Highest-revenue month?
SELECT MONTHNAME(INVOICE_DATE) AS MONTH ,SUM(MARGIN) AS HIGHEST_REVENUE_MONTH FROM `INDIAN FMCG`
GROUP BY MONTHNAME(INVOICE_DATE) ORDER BY (SUM(MARGIN)) desc LIMIT 1;

#Revenue by city?
SELECT CITY,SUM(REVENUE) AS REVENUE FROM `INDIAN FMCG`
GROUP BY (CITY) ORDER BY SUM(REVENUE) DESC
#Profit by city?
SELECT CITY,SUM(MARGIN) AS MARGIN FROM `INDIAN FMCG`
GROUP BY (CITY) ORDER BY SUM(MARGIN) DESC
#Revenue by category?
SELECT CATEGORY,SUM(REVENUE) AS REVENUE FROM `INDIAN FMCG`
GROUP BY (CATEGORY) ORDER BY SUM(REVENUE) DESC
#Profit by category?
SELECT CATEGORY,SUM(MARGIN) AS MARGIN FROM `INDIAN FMCG`
GROUP BY (CATEGORY) ORDER BY SUM(MARGIN) DESC
#Top 10 brands by revenue?
SELECT BRAND,SUM(REVENUE) AS REVENUE FROM `INDIAN FMCG`
GROUP BY (BRAND) ORDER BY SUM(REVENUE) DESC LIMIT 10;
#Top 10 brands by profit?
SELECT BRAND,SUM(MARGIN) AS MARGIN FROM `INDIAN FMCG`
GROUP BY (BRAND) ORDER BY SUM(MARGIN) DESC LIMIT 10;
#Online vs Offline performance?
SELECT CHANNEL,SUM(UNITS) AS UNITS,SUM(REVENUE) AS REVENUE,SUM(MARGIN) AS MARGIN FROM `INDIAN FMCG`
GROUP BY (CHANNEL)
#Loyalty vs non-loyalty revenue?
SELECT CASE 
			WHEN LOYALTY_FLAG='0' THEN 'non-loyalty'
            WHEN LOYALTY_FLAG='1' THEN 'loyalty'
            END AS LOYALTY_FLAG,SUM(REVENUE) AS REVENUE FROM `INDIAN FMCG`
GROUP BY LOYALTY_FLAG
#Revenue by gender?
SELECT CUSTOMER_GENDER ,SUM(REVENUE) FROM `INDIAN FMCG`
GROUP BY CUSTOMER_GENDER

#Which records are below reorder level?
SELECT * FROM `INDIAN FMCG`
WHERE STOCK_ON_HAND < REORDER_LEVEL

SELECT * FROM `INDIAN FMCG`